---
# Update the iDRAC and BIOS on Dell FC630 servers
# The BIOS update requires a reboot so put it last
# The dell-update role expect to find the required files in the `files/`
# sub-directory of the role. Set dell_update_package_dir to override it.

- hosts: all
  roles:
  - role: dell-update
    dell_update_filename: iDRAC-with-Lifecycle-Controller_Firmware_4950Y_LN_2.41.40.40_A00.bin
  - role: dell-update
    dell_update_filename: BIOS_DH7R1_LN_2.4.2.bin

  # vars:
  # - dell_update_package_dir: ~/ansible-data/dell-fc630/
