---
- name: system-base-update (freebsd) | Fetch new FreeBSD updates
  command: freebsd-update fetch --not-running-from-cron
  register: result_update
  changed_when: "'No updates needed' not in result_update.stdout"
  become: yes

- name: system-base-update (freebsd) | Install FreeBSD updates
  command: freebsd-update install
  when: ansible_distribution == 'FreeBSD' and result_update.changed
  register: result_update_install
  become: yes
  notify:
    - reboot
    - wait for restart
    - wait for ssh
