---
- include: darwin.yml
  when: ansible_os_family == 'Darwin'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: freebsd.yml
  when: ansible_os_family == 'FreeBSD'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: windows.yml
  when: ansible_os_family == 'Windows'
