---
# Install all security, critical, and rollup updates
- name: system-base-update (windows) | Install Windows updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
