---
# cloudinit installs python2.7, but not the base python and python2 links.
- name: ci-base-setup (freebsd) | Install python
  pkgng:
    name: python
    state: present
  become: yes

- name: ci-base-setup (freebsd) | Mount fdescfs
  mount:
    path: /dev/fd
    src: fdesc
    fstype: fdescfs
    opts: rw
    state: mounted
  become: yes

- name: ci-base-setup (freebsd) | Mount procfs
  mount:
    path: /proc
    src: proc
    fstype: procfs
    opts: rw
    state: mounted
  become: yes
