---
- name: ci-jenkins-workspace (freebsd) | Add jenkins dataset
  zfs:
    name: scratch/jenkins
    state: present
    compression: lz4
    devices: off
    setuid: off
    atime: off
    sync: disabled
  become: yes

- name: ci-jenkins-workspace (freebsd) | Add workspace dataset
  zfs:
    name: scratch/jenkins/workspace
    state: present
    compression: lz4
    devices: off
    setuid: off
    atime: off
    sync: disabled
  become: yes

- name: ci-jenkins-workspace (freebsd) | Set jenkins dataset ownership
  file:
    path: /scratch/jenkins
    owner: "{{ ci_jenkins_user }}"
    group: "{{ ci_jenkins_group }}"
    mode: 0775
  become: yes

- name: ci-jenkins-workspace (freebsd) | Set workspace dataset ownership
  file:
    path: /scratch/jenkins/workspace
    owner: "{{ ci_jenkins_user }}"
    group: "{{ ci_jenkins_group }}"
    mode: 0775
  become: yes
