---
- name: pkg-java-tools (debian) | Install Java build tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ant
    - maven
  become: yes

- name: pkg-java-tools (debian) | Install Java testing tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - findbugs
    - junit4
  become: yes
