---
- name: pkg-java-tools (freebsd) | Install Java build tools
  pkgng:
    name: apache-ant,maven
    state: present
  become: yes

- name: pkg-java-tools (freebsd) | Install Java testing tools
  pkgng:
    name: java-findbugs,junit
    state: present
  become: yes
