---
- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: linux.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: freebsd.yml
  when: ansible_os_family == 'FreeBSD'
