---
# Playbook for running all IDR deployment playbooks

- include: idr-analysis.yml
- include: idr-docker.yml
- include: idr-gpfs-client.yml
- include: idr-nfs-hosts.yml
- include: idr-samba-hosts.yml
