---
# Playbook for running all IDR playbooks

# Initial networking and basic system configuration
# A reboot may be required after this playbook
- include: idr-initial.yml

# Upgrade all system packages
# A reboot may be required after this playbook
- include: idr-upgrade.yml

# Install everything else
- include: idrsystems-deployment.yml
