---
- name: ci-jenkins-service (windows) | Remove Jenkins service
  win_nssm:
    name: jenkins
    state: absent
  environment:
    PATH: "{{ tools_location }}\\sbin;{{ ansible_env.Path }}"

# Download after the service is stopped, or the file will be in use.
- name: ci-jenkins-service (windows) | Download the Jenkins slave jar
  win_get_url:
    url: "http://{{ jenkins_master }}:8080/jnlpJars/slave.jar"
    dest: "{{ jenkins_location }}\\slave.jar"

- name: ci-jenkins-service (windows) | Change owner of Jenkins slave jar
  win_owner:
    path: "{{ jenkins_location }}\\slave.jar"
    user: "{{ ci_jenkins_user }}"

# win_nssm had quoting issues, so run by hand.
- name: ci-jenkins-service (windows) | Add Jenkins service
  win_command: "{{ tools_location }}\\sbin\\nssm.exe install jenkins \\\"C:\\Program Files\\ojdkbuild\\java-1.8.0-openjdk-1.8.0.121-2\\bin\\java.exe\\\" -jar \"{{ jenkins_location }}\\slave.jar\" -jnlpUrl http://{{ jenkins_master }}:8080/computer/{{ jenkins_slave.name }}/slave-agent.jnlp -secret {{ jenkins_slave.authtoken }}"

- name: ci-jenkins-service (windows) | Set Jenkins service startup directory
  win_command: "{{ tools_location }}\\sbin\\nssm.exe set jenkins AppDirectory \"{{ jenkins_location }}\""

- name: ci-jenkins-service (windows) | Set Jenkins service user
  win_command: "{{ tools_location }}\\sbin\\nssm.exe set jenkins ObjectName .\\{{ ci_jenkins_user }} {{ ci_jenkins_password }}"

- name: ci-jenkins-service (windows) | Set Jenkins environment
  win_command: "{{ tools_location }}\\sbin\\nssm.exe set jenkins AppEnvironmentExtra \\\"PATH=C:\\Program Files\\Git\\bin;C:\\Program Files\\CMake\\bin;{{ tools_location }}\\bin;{{ ansible_env.Path }}\\\""

- name: ci-jenkins-service (windows) | Start Jenkins service
  win_service:
    name: jenkins
    start_mode: auto
    state: started
