---
- name: ci-scratch-storage (debian) | Install LVM
  apt:
    name: lvm2
    state: present
  become: yes

- name: ci-scratch-storage (debian) | Create volume group
  lvg:
    pvs: /dev/vdb
    state: present
    vg: scratch
  become: yes
