---
- name: ci-scratch-storage (windows) | Check that the drive S exists
  win_stat: path='S:/'
  register: stat_drive

- name: ci-scratch-storage (windows) | Create diskpart script
  win_copy:
    src: win-scratch-diskpart
    dest: "{{ ansible_user_dir }}\\scratch-diskpart"
  when: stat_drive.stat.exists == False
 
- name: ci-scratch-storage (windows) | Create S drive
  win_command: "diskpart /s {{ ansible_user_dir }}\\scratch-diskpart"
  when: stat_drive.stat.exists == False

- name: ci-scratch-storage (windows) | Delete diskpart script
  win_file:
    path: "{{ ansible_user_dir }}\\scratch-diskpart"
    state: absent
  when: stat_drive.stat.exists == False
