# Install OMERO.web with a public user on localhost

- hosts: all

  roles:

#    # Root LV Size 
#    - role: openmicroscopy.lvm-partition
#      lvm_lvmount: /
#      lvm_lvsize: "{{ provision_rootsize }}"
#      lvm_lvfilesystem: "{{ provision_root_filesystem }}"
#


    # OMERO.web configuration in host_vars in different repository
    - role: openmicroscopy.omero-web
      omero_web_release: 5.3.0-m9

    - role: openmicroscopy.system-monitor-agent
      when: >
            ((ansible_env.COBBLER_SERVER is defined)
            and (ansible_env.COBBLER_SERVER == "spacewalk.lifesci.dundee.ac.uk"))

