---
dependency:
  name: galaxy
  requirements_file: requirements.yml

driver:
  name: docker

docker:
  containers:
  - name: omero-server
    image: centos/systemd
    image_version: latest
    privileged: True

ansible:
  host_vars:
    omero-server:
      omero_server_systemd_require_network: False
  verbose: True
  diff: True

verifier:
  name: testinfra
