# Install OMERO.server and prepare the OME (UoD/SLS) prerequisites

- hosts: all
  pre_tasks:
    - name: Install open-vm-tools if system is a VMware vm
      become: yes
      yum:
        name: open-vm-tools
        state: latest
      when: >
           ((ansible_virtualization_type is defined)
           and (ansible_virtualization_type == "VMware"))
   
  roles:
    # Now OME are using RHEL without Spacewalk, the current best-method of
    # checking `is server SLS` is checking for the SLS nameservers.
    - role: openmicroscopy.system-monitor-agent
      when: "'10.1.255.216' in ansible_dns.nameservers"

    # Disk Layout - PostgreSQL | data dir  
    - role: openmicroscopy.lvm-partition
      tags: lvm
      lvm_lvname: pgdata
      lvm_vgname: postgresql
      lvm_lvmount: /var/lib/pgsql
      lvm_lvsize: "74G"
      lvm_lvfilesystem: "{{ filesystem }}"

    # Disk Layout - OMERO | data dir 
    - role: openmicroscopy.lvm-partition
      tags: lvm
      lvm_lvname: basedir
      lvm_vgname: omero
      lvm_lvmount: "{{ omero_common_basedir }}"
      lvm_lvsize: "10120M"
      lvm_lvfilesystem: "{{ filesystem }}"
      
    #  Mock database user & creds, to allow Playbook to install
    #  OMERO, and allow for a manual PostgresSQL dump/restore.
    - role: openmicroscopy.postgresql
      postgresql_users_databases:
      - user: install-mock
        password: install-mock
        databases: [install-mock]

    # Testing with the NS copied data will require
    # a 5.2.x server, to be upgraded later.
    # Note - had to have these set to `install-mock` to progress role
    # installation before changing config to restored DB from other system.
    - role: openmicroscopy.omero-server
      omero_server_release: 5.2.8
      omero_server_dbuser: "{{ vault_omero_server_os_user }}"
      omero_server_dbname:  "{{ vault_omero_server_dbname }}"
      omero_server_dbpassword: "{{ vault_omero_server_dbpassword }}"
      # Active Directory users not working with role
      # Role requires to be manually modified to make it work with an AD user
      omero_server_system_user: "{{ vault_omero_server_os_user }}"
      # omero_server_datadir: overridden after inital role run, via host vars

  vars:
    postgresql_version: "9.6"
    filesystem: "xfs"
    omero_server_config_set:
      omero.db.poolsize: 60
      omero.jvmcfg.percent.blitz: 50
      omero.jvmcfg.percent.indexer: 20
      omero.jvmcfg.percent.pixeldata: 20
      omero.jvmcfg.system_memory: 17000
      omero.ldap.base: "{{ omero_server_ldap_base }}"
      omero.ldap.config: true
      omero.ldap.new_user_group: default
      omero.ldap.urls: "{{ omero_server_ldap_urls }}"
      omero.mail.config: true
      omero.mail.from: "{{ omero_server_mail_from }}"
      omero.mail.host: "{{ omero_server_mail_host }}"
      omero.new_user_group: "My Data"
      omero.search.batch: 100
      omero.security.password_provider: chainedPasswordProvider431
      omero.throttling.method_time.error: 60000
 
