---
- name: ci-admin-user (linux) | Add ci-admin to sudoers
  copy:
    src: 90-ome-admin-users
    dest: /etc/sudoers.d/90-ome-admin-users
    owner: root
    group: wheel
    mode: 0440
  become: yes
