---
- include_tasks: unix.yml
  when: ansible_os_family != 'Windows'

- include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- include_tasks: linux.yml
  when: ansible_system == 'Linux'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: freebsd.yml
  when: ansible_os_family == 'FreeBSD'

- include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
