---
- include: unix.yml
  static: no
  when: ansible_os_family != 'Windows'

- include: linux.yml
  static: no
  when: ansible_system == 'Linux'

- include: debian.yml
  static: no
  when: ansible_os_family == 'Debian'

- include: freebsd.yml
  static: no
  when: ansible_os_family == 'FreeBSD'

- include: windows.yml
  static: no
  when: ansible_os_family == 'Windows'
