---
- include_tasks: linux.yml
  when: ansible_system == 'Linux'

- include_tasks: freebsd.yml
  when: ansible_os_family == 'FreeBSD'

- include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
