# Install NGINX, and prepare the OME (UoD/SLS) prerequisites

- hosts: infra-testpr.openmicroscopy.org
  environment:
      PATH: /usr/local/bin:{{ ansible_env.PATH }}
  pre_tasks:
    - name: Install open-vm-tools if system is a VMware vm
      become: yes
      yum:
        name: open-vm-tools
        state: latest
      when: >
           ((ansible_virtualization_type is defined)
           and (ansible_virtualization_type == "VMware"))

    # Perhaps alter the role at https://github.com/openmicroscopy/ansible-role-lvm-partition/
    # to make some of the variables non-required.
    - name: Resize root FS without altering mount options
      tags: lvm
      become: yes
      lvol:
        lv: root
        vg: VolGroup00
        size: "{{ provision_root_lvsize }}"
        shrink: no

    - name: NGINX - SSL File Deployment - prepare directory
      become: yes
      file:
        path: "{{ nginx_ssl_files_path }}"
        state: directory
        owner: root
        group: root
        mode: "u=r,go=" 

    - name: NGINX - SSL File Deployment
      become: yes
      copy:
        dest="{{ item.key }}"
        content="{{ item.value.content }}"
        owner="{{ item.value.owner }}"
        group="{{ item.value.group }}"
        mode="{{ item.value.mode }}"
      with_dict: "{{ nginx_ssl_cert_files }}"
      no_log: true



  roles:
    # Now OME are using RHEL without Spacewalk, the current best-method of
    # checking `is server deployed in Dundee/SLS` is checking for the SLS nameservers.
    - role: openmicroscopy.system-monitor-agent
      tags: monitoring
      when: "'10.1.255.216' in ansible_dns.nameservers"

    - role: openmicroscopy.jekyll-build
      tags: jekyll
      jekyll_build_git_repo: "https://github.com/snoopycrimecop/www.openmicroscopy.org"
      jekyll_build_git_branch: "gh-pages"
      jekyll_build_force_rebuild: True

    - role: openmicroscopy.nginx_proxy
      tags: nginxconf
      nginx_proxy_worker_processes: "{{ ((ansible_processor_count * ansible_processor_cores) / 2) |round|int }}"
      nginx_proxy_ssl: True
      nginx_proxy_ssl_certificate: "{{ nginx_ssl_files_path }}/{{ nginx_ssl_cert_filename }}"
      nginx_proxy_ssl_certificate_key: "{{ nginx_ssl_files_path }}/{{ nginx_ssl_key_filename }}"
      nginx_proxy_http2: True
      nginx_proxy_force_ssl: False
      nginx_proxy_hsts_age: 31536000

    #- role: openmicroscopy.nginx
   
  post_tasks:

    # TODO define this in a variable from host_vars, as varies per-host
    # and we are also using it in the config for role openmicroscopy.jekyll-build
    - name: Deployed HTML Symlink
      become: yes
      tags: jekyll
      file:
        src: /var/www/localhost/html/
        path: /var/www/localhost/html/www.openmicroscopy.org
        state: link

    - name: NGINX - Performance tuning - worker processes
      become: yes
      replace:
        path: "/etc/nginx/nginx.conf"
        regexp: '^worker_processes\s+\d+;'
        replace: "worker_processes {{ ((ansible_processor_count * ansible_processor_cores) / 2) |round|int }};"

    # cf https://www.digitalocean.com/community/tutorials/how-to-optimize-nginx-configuration
    - name: NGINX - Performance tuning - worker connections
      become: yes
      replace:
        path: "/etc/nginx/nginx.conf"
        regexp: 'worker_connections\s+\d+;'
        replace: "worker_connections 65000;"
            
    - name: Check_MK logwatch plugin | check for plugin existence
      tags: monitoring
      stat:
        path: "{{ check_mk_agent_plugin_path }}/mk_logwatch"
      register: check_mk_logwatch_plugin_st

    - name: Check_MK logwatch plugin | activate the plugin
      tags: monitoring
      become: yes
      command: cp "{{ check_mk_agent_plugin_path }}/mk_logwatch" /usr/share/check-mk-agent/plugins/ creates=/usr/share/check-mk-agent/plugins/mk_logwatch
      when: check_mk_logwatch_plugin_st.stat.exists

    - name: Check_MK logwatch plugin | check for default config file
      tags: monitoring
      stat:
        path: "{{ check_mk_agent_config_example_path }}/logwatch.cfg"
      register: check_mk_logwatch_plugin_conf_st
      
    - name: Check_MK logwatch plugin | copy the default config
      tags: monitoring
      become: yes
      command: cp "{{ check_mk_agent_config_example_path }}/logwatch.cfg" "{{ check_mk_agent_config_path }}/logwatch.cfg" creates="{{ check_mk_agent_config_path }}/logwatch.cfg"
      when: check_mk_logwatch_plugin_conf_st.stat.exists

  vars:
    vault: "{{ lookup('passwordstore', 'vault/{{ inventory_hostname }} returnall=True') | from_yaml }}"
    # Check_MK (system monitoring) paths
    check_mk_agent_plugin_path: /usr/share/check-mk-agent/available-plugins
    check_mk_agent_config_example_path: /usr/share/check_mk/agents/cfg_examples
    check_mk_agent_config_path: /etc/check-mk-agent

    filesystem: "xfs"
    
    # Vars for role openmicroscopy.nginx_proxy
    nginx_proxy_backends:
      - location: /community
        server: http://www-legacy.openmicroscopy.org/community
      - location: /qa2
        server: http://www-legacy.openmicroscopy.org/qa2
      - location: /Schemas
        server: http://www-legacy.openmicroscopy.org/Schemas
      - location: /XMLschemas
        server: http://www-legacy.openmicroscopy.org/XMLschemas
      - location: /omero-blog
        server: http://blog.openmicroscopy.org
      - location: /site/support/omero
        server: http://www-legacy.openmicroscopy.org/site/support/omero
      - location: /site/support/omero5
        server: http://www-legacy.openmicroscopy.org/site/support/omero5
      - location: /site/support/omero5.3
        server: http://www-legacy.openmicroscopy.org/site/support/omero5.3
      - location: /site/support/bio-formats
        server: http://www-legacy.openmicroscopy.org/site/support/bio-formats
      - location: /site/support/bio-formats5
        server: http://www-legacy.openmicroscopy.org/site/support/omero5
      - location: /site/support/bio-formats5.5
        server: http://www-legacy.openmicroscopy.org/site/support/bio-formats5.5
      - location: /site/support/ome-model
        server: http://www-legacy.openmicroscopy.org/site/support/ome-model
      - location: /site/support/contributing
        server: http://docs.openmicroscopy.org/contributing
      - location: /site/support/ome-files-cpp
        server: http://www-legacy.openmicroscopy.org/site/support/ome-files-cpp
      - location: /site/products/omero/secvuln
        server: http://www-legacy.openmicroscopy.org/site/products/omero/secvuln

    nginx_proxy_redirect_map_locations:
    # TODO: change to 301 when we're happy
    - location: "~ ^/(site/about)($|/)"
      code: 302
    - location: "~ ^/(site/products)($|/)"
      code: 302
    - location: "~ ^/(site/community)($|/)"
      code: 302
    - location: "~ ^/(site/news)($|/)"
      code: 302

    nginx_proxy_redirect_map:
    - match: default
      dest: /404.html
    # about
    - match: /site/about
      dest: /about
    - match: /site/about/who-ome
      dest: /about
    - match: /site/about/licensing-attribution
      dest: /licensing
    - match: /site/about/ome-contributors
      dest: /contributors
    - match: /site/about/partners
      dest: /commercial-partners
    - match: /site/about/development-teams
      dest: /teams

    # products
    - match: /site/products
      dest: /products
    - match: /site/products/omero
      dest: /omero
    - match: /site/products/omero/feature-list
      dest: /omero/new
    - match: /site/products/omero/big-images-support
      dest: /omero/view/
    - match: /site/products/bio-formats
      dest: /bio-formats
    - match: /site/products/ome-files-cpp
      dest: /ome-files

    # community
    - match: /site/community
      dest: /support
    - match: /site/community/mailing-lists
      dest: /support
    - match: /site/community/jobs
      dest: /careers

    # misc
    - match: /site/news
      dest: /announcements
    

    nginx_proxy_direct_locations:
    - location: "/"
      root: /var/www/localhost/html
      index: index.html
