---
- name: system-package-update (homebrew) | Update and upgrade packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: system-package-update (homebrew) | Clean up
  command: brew cleanup

- name: system-package-update (homebrew) | Prune stale links
  command: brew prune

- name: system-package-update (homebrew) | Check for problems
  command: brew doctor
