---
- include_tasks: homebrew.yml
  when: ansible_pkg_mgr is defined and ansible_pkg_mgr == 'homebrew'
  become: true
  become_user: "{{homebrew_user}}"
  environment:
    PATH: "/usr/local/bin:/usr/local/sbin:{{ ansible_env.PATH }}"

- include_tasks: apt.yml
  when: ansible_pkg_mgr is defined and ansible_pkg_mgr == 'apt'

- include_tasks: pkgng.yml
  when: ansible_pkg_mgr is defined and ansible_pkg_mgr == 'pkgng'

- include_tasks: yum.yml
  when: ansible_pkg_mgr is defined and ansible_pkg_mgr == 'yum'
