---
- name: system-package-update (freebsd) | Update package list
  command: pkg update -q
  become: yes

- name: system-package-update (freebsd) | Upgrade packages
  command: pkg upgrade -y
  become: yes

- name: system-package-update (freebsd) | Clean package cache
  command: pkg clean -qy
  become: yes
