---
# Playbook for provisioning Devspace

- hosts: devspace

  vars:
    # Overrides the default value in the docker role
    docker_use_ipv4_nic_mtu: True

  vars_prompt:
    - name: "devspace_jenkins_password"
      prompt: "Secure Jenkins with admin password (username: devspace)"
      private: yes

  pre_tasks:

    - fail:
        msg: "Jenkins admin password is required"
      when: devspace_jenkins_password is undefined or not devspace_jenkins_password

  roles:
    - role: openmicroscopy.devspace
