---
# Playbook for preparing IDR openstack nodes

# idr-initial.yml must have already been run

- hosts: idr-openstack

  roles:
  - role: network
  - role: logrotate
  - role: system-monitor-agent
  - role: mysql-backup
    when: "{{ openstack_master_node | default(False) }}"

  vars:
    network_ifaces: "{{ post_network_ifaces }}"

  tasks:
    - name: add extra packages
      become: yes
      yum:
        name: jq
        state: present
