---
- name: ci-jenkins-service (windows) | Download the Jenkins slave jar
  win_get_url:
    url: 'http://134.36.162.56:8080/jnlpJars/slave.jar'
    dest: '{{ jenkins_location }}\slave.jar'

- name: ci-jenkins-service (windows) | Change owner of Jenkins slave jar
  win_owner: path={{ jenkins_location }}\slave.jar user={{ ci_jenkins_user }} recurse=yes

- name: ci-jenkins-service (windows) | Remove Jenkins service
  win_nssm:
    name: jenkins
    state: absent
  environment:
    PATH: "{{ tools_location }}\\sbin;{{ ansible_env.Path }}"

# win_nssm had quoting issues, so run by hand.
- name: ci-jenkins-service (windows) | Add Jenkins service
  win_command: '{{ tools_location }}\sbin\nssm.exe install jenkins \"C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.121-2\bin\java.exe\" -jar \"{{ jenkins_location }}\slave.jar\" -jnlpUrl http://134.36.162.56:8080/computer/win-vs2017/slave-agent.jnlp -secret a03f3a4cf5739289943338e8e42a62fab5ce2d8f7d9e74c82f0be302b0ba030f'

- name: ci-jenkins-service (windows) | Set Jenkins service startup directory
  win_command: '{{ tools_location }}\sbin\nssm.exe set jenkins AppDirectory \"{{ jenkins_location }}\"'

- name: ci-jenkins-service (windows) | Set Jenkins service user
  win_command: '{{ tools_location }}\sbin\nssm.exe set jenkins ObjectName .\{{ ci_jenkins_user }} OME$%9723@'

- name: ci-jenkins-service (windows) | Start Jenkins service
  win_service:
    name: jenkins
    start_mode: auto
    state: started
