---
- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: freebsd.yml
  when: ansible_os_family == 'FreeBSD'

- include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
