---
- name: reboot
  command: shutdown -r now "ansible triggered restart"
  become: yes

- name: wait for restart
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 30
    timeout: 320
    state: started

- name: wait for ssh
  local_action:
    module: pause
    seconds: 5
