---

- name: openmicroscopy.nginx
  src:  https://github.com/openmicroscopy/ansible-role-nginx.git

- name: openmicroscopy.nginx_proxy
  src: https://github.com/snoopycrimecop/ansible-role-nginx-proxy.git
  version: master/merge/daily

# dependancy of nginx_proxy
- name: openmicroscopy.selinux-utils
  src: https://github.com/openmicroscopy/ansible-role-selinux-utils.git
  version: 1.0.3

- name: openmicroscopy.jekyll-build
  src: https://github.com/openmicroscopy/ansible-role-jekyll-build.git
  version: 1.2.0

- name: openmicroscopy.lvm-partition
  src: https://github.com/openmicroscopy/ansible-role-lvm-partition.git

- name: openmicroscopy.system-monitor-agent
  src: https://github.com/openmicroscopy/ansible-role-system-monitor-agent.git


