---

- name: restart devspace
  environment:
    USER_ID: "{{ devspace_user_id }}"
    JENKINS_USERNAME: "{{ devspace_jenkins_username }}"
    JENKINS_PASSWORD: "{{ devspace_jenkins_password }}"
  become: yes
  become_user: "{{ devspace_user }}"
  include: "{{ devspace_handler_tasks }}"
