---
- include: debian.yml
  static: no
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  static: no
  when: ansible_os_family == 'RedHat'

- include: freebsd.yml
  static: no
  when: ansible_os_family == 'FreeBSD'

- include: windows.yml
  static: no
  when: ansible_os_family == 'Windows'
