---
- name: ci-base-setup (windows) | Get domain
  win_shell: "net config workstation | findstr /C:\"Full Computer name\" | %{$_ -replace \"^Full Computer name *\",\"\"}"
  register: win_domain

- name: ci-base-setup (windows) | Set domain
  win_shell: "netdom computername $env:computername /add:{{ inventory_hostname }}"
  when: (inventory_hostname != win_domain.stdout.rstrip())

- name: ci-base-setup (windows) | Set primary domain
  win_shell: "netdom computername $env:computername /makeprimary:{{ inventory_hostname }}"
  when: (inventory_hostname != win_domain.stdout.rstrip())

- name: ci-base-setup (windows) | Remove old domain
  win_shell: "netdom computername $env:computername /remove:{{ win_domain.stdout.rstrip() }}"
  when: (inventory_hostname != win_domain.stdout.rstrip())

- name: ci-base-setup (windows) | Get hostname
  win_command: hostname
  register: win_hostname

- name: ci-base-setup (windows) | Set hostname
  win_shell: "netdom renamecomputer $env:computername /newname:{{ inventory_hostname.split('.')[0] }} /force"
  when: (inventory_hostname.split('.')[0] != win_hostname.stdout.rstrip())

- name: ci-base-setup (windows) | Export security policy
  win_command: "secedit /export /cfg {{ ansible_user_dir }}\\secpol.cfg"

- name: ci-base-setup (windows) | Update security policy to relax password rules and match Unix hosts
  win_lineinfile:
    dest: "{{ ansible_user_dir }}\\secpol.cfg"
    regexp: '^PasswordComplexity =.*'
    line: 'PasswordComplexity = 0'
  register: secpol

- name: ci-base-setup (windows) | Import security policy
  win_command: "secedit /configure /db c:\\windows\\security\\local.sdb /cfg {{ ansible_user_dir }}\\secpol.cfg /areas SECURITYPOLICY"
  when: secpol.changed

- name: ci-base-setup (windows) | Delete exported security policy
  win_file:
    path: "{{ ansible_user_dir }}\\secpol.cfg"
    state: absent

- name: ci-base-setup (windows) | Reboot
  win_reboot:
  when: (inventory_hostname != win_domain.stdout.rstrip() or inventory_hostname.split('.')[0] != win_hostname.stdout.rstrip())
